fail_fast: false
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-tabs
        exclude: "vendor-prefixes\\.txt$|.git/COMMIT_EDITMSG"
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args:
          - -i
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: |
          (?x)^(
              .git/COMMIT_EDITMSG|
              CHANGELOG.md|
              .release-please-manifest.json
          )$
        # Workaround for https://github.com/pre-commit/mirrors-prettier/issues/29
        additional_dependencies:
          - prettier@2.8.7
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
        exclude: "\\.mustache$"
  - repo: https://github.com/Quard/license-header-checker
    rev: v0.2.1
    hooks:
      - id: license-header-checker
        files: \.(c|h|dtsi|dts|overlay|keymap)$
        exclude: ^((app/boards/)|(app/tests/))
        args:
          - --comment-style
          - "/*| *| */"
          - --license
          - "\\nCopyright \\(c\\) \\d{4}(-\\d{4})? The ZMK Contributors\\n\\nSPDX-License-Identifier: MIT\\n"
          - --auto-populate
          - .pre-commit/license_header.tmpl
      - id: license-header-checker
        files: (\.yaml)|(CMakeLists.txt)|(Kconfig)$
        exclude: ^((app/boards/)|(app/tests/)|(\.pre-commit-config.yaml))
        args:
          - --comment-style
          - "#"
          - --license
          - "\\s*Copyright \\(c\\) \\d{4}(-\\d{4})? The ZMK Contributors\\n\\s*SPDX-License-Identifier: MIT"
          - --auto-populate
          - .pre-commit/license_header.tmpl
